apiVersion: apps/v1
kind: Pod
metadata:
  name: hsitpod1
  labels:
    name: hsitpod1
    app: histapp
spec:
  containers:
  - name: hsitpod1
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
